### ISSUE TITLE
Please fill out `description:` field

### ISSUE THREAD

**Issue by hvr** [wangbj/hashing#1]
As you can see on https://hackage.haskell.org/package/hashing-0.1.0.0, the description says "Please see README.md". If you upload packages to Hackage, you're expected to write a short abstract in the `description` field. An optional `README` does not replace the `description` field, but rather expands on it, since most tooling doesn't have access to the `README`, and in that context referring to an inaccessible `README` is rather pointless.

It would probably also be a good idea to point out how your implementation compares to the already existing (and very popular) pure Haskell implementations:
- http://hackage.haskell.org/package/pureMD5
- http://hackage.haskell.org/package/SHA

PS: You should also add a `bug-reports` field to your `.cabal` file, e.g.

```
bug-reports: https://github.com/wangbj/hashing/issues
```

**Comment by wangbj** [comment]
Thanks a lot for the feedback. This is my first package on hackage. I've updated .cabal file to the master branch (6ae650d), can you check if it's OK? More reason behind is I've spent about 2 years learning haskell by now, and realized it would be better start to write something.

**Comment by hvr** [comment]
@wangbj looks generally good, except for

```
synopsis: Initial project template from stack
```

this should be a short single-line (ideally under 80 character) blurb which appears in package-lists, e.g. on http://hackage.haskell.org/packages/search?terms=hashing

the other thing is that it's good practice to specify upper bounds limiting the major version
(c.f. https://wiki.haskell.org/Package_versioning_policy)

So rather than

```
build-depends:  array >= 0.5.1.0, bytestring >= 0.10.6.0
```

use something like

```
build-depends:  array >= 0.5.1.0 && < 0.6, bytestring >= 0.10.6.0 && < 0.11
```

**Comment by wangbj** [comment]
Done(656dd2f). Thanks a lot for the suggestions.

**Comment by wangbj** [comment]
.cabal file updated for better hackage integration
